name: Auto Assign PRs to Project

on:
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/jwMaxwell/Spike-2/projects/1'
        column_name: 'Needs Review'